### ISSUE TITLE
Notifications for new releases

### ISSUE THREAD

**Issue by turbobabr** [turbobabr/sketch-devtools#10]
This one is must have, but I still can't figure out how to implement it. It also would be nice to have auto update feature, but not now. Here is the quick sketch for notification about new release I came up with:

![bitmap](https://cloud.githubusercontent.com/assets/6356526/4515014/09e47f46-4ba2-11e4-876e-7c1cd35fdd3f.png)

Clicking on "GET IT NOW!" button just opens a default browser on a specific GitHub page in the repo with update instructions.

**Comment by turbobabr** [comment]
![bitmap current result](https://cloud.githubusercontent.com/assets/6356526/4821116/b6fd1afe-5f24-11e4-832f-1f00a92ab78f.png)

**Comment by phaistonian** [comment]
So you DID figure out how to implement it after all or is it just you teasing poor us?:)

**Comment by turbobabr** [comment]
It's implemented and working.. I'm still waiting for someone to help me with #24 to fix it prior release. But something really strange happens with this issue. People report about it, but no one wants to participate and help me to reproduce it. :)

**Comment by phaistonian** [comment]
I _wish_ I had this issue so I could be of help, yet things are working great here.

If I can be of help - of any help - please let me know :)

ps: Can we haz the changelog of the new version ?:)

**Comment by turbobabr** [comment]
The change log on a picture above is the real one. Just bug fixes, nothing fancy and cool. :)

**Comment by turbobabr** [comment]
Will release it in a few days without the bug fix I'd just talked about.

**Comment by phaistonian** [comment]
Those are sweet & great enough :-)

btw, how about fetching notifications for new releases for new the "Dev Tools assistant" too? 

Those two go together so that'd make some sense too.

**Comment by turbobabr** [comment]
Great idea! Will fill the ticket.. :)
