### ISSUE TITLE
Invalid module imports don't work as expected

### ISSUE THREAD

**Issue by turbobabr** [turbobabr/sketch-devtools#20]
It seems that `MSPlugin.scriptWithExpandedImports:path: method` resolves paths differently than my implementation. Here is the result I get when running an old plugin that actually works in sketch:
![bitmap](https://cloud.githubusercontent.com/assets/6356526/4717350/c0d2402a-5913-11e4-89a7-550cb5425187.png)

Should turn off the whole imports checking module and revisit it later.

**Comment by getflourish** [comment]
Not sure if it’s is related to this topic, but plugins that have imports don’t work anymore as soon as the console did open. Dev Tools Console says the Script executed but nothing really happens. Log from OS X console: 

24/10/14 20:56:09,223 Sketch[4733]: -[TDToken quotedString]: unrecognized selector sent to instance 0x60000185b300

24/10/14 20:56:09,223 Color Inventory (Sketch Plugin)[4733]: Caught script exception: -[TDToken quotedString]: unrecognized selector sent to instance 0x60000185b300

**Comment by turbobabr** [comment]
Holy crap! Thank you for reporting this. Will try to fix it ASAP!

**Comment by turbobabr** [comment]
Florian,

I've found a problem, and now it works like a charm! :)
Here is the proof: 
![bitmap](https://cloud.githubusercontent.com/assets/6356526/4804924/3d4e9b24-5e75-11e4-894a-99ea2c834411.png)

The fix isn't published yet, because I have to ask a few questions to Sam about file paths resolving mechanism. I think that fix will be available tomorrow.

**Comment by getflourish** [comment]
Great! Thanks buddy :)
