### ISSUE TITLE
Live updates

### ISSUE THREAD

**Issue by phaistonian** [turbobabr/sketch-devtools#21]
(Optionally?)

Re-run plugin when focus is set back to Sketch after updates are introduced via the external editor (e.g Sublime Text).

**Comment by Arkkimaagi** [comment]
This should definitely be an option as running a plugin automatically can cause havoc on your document.

**Comment by Arkkimaagi** [comment]
Maybe we could have plugins for our editors to run some code in Sketch while in the editor?
