### ISSUE TITLE
On "updating plugins"

### ISSUE THREAD

**Issue by phaistonian** [turbobabr/sketch-devtools#23]
This is a bit sci-fi, but hey, you can just ignore it :)

What if there were an option (accessible probably via the gear icon) that would run through all plugins in plugin directory and if any of those has an endpoint defined (be that .git or a .skethplugin URI), then auto-update by refetching from given endpoint.

![image](https://cloud.githubusercontent.com/assets/796530/4769435/ce3e8cc4-5b79-11e4-9680-164c1b263f4e.png)

Not sure this makes any sense, but if this does and it gets implemented (and adopted), stress-free updates would be one click away :)

**Comment by turbobabr** [comment]
Great idea, but it's definitely out of the scope of this solution, since it's a just a set of dev utilities that helps to develop and debug plugins. What you are talking is the full-fledged plugins management system that is a whole new story! :)
