### ISSUE TITLE
Support for Sketch Beta

### ISSUE THREAD

**Issue by uetchy** [turbobabr/sketch-devtools#28]
Can I use Sketch-DevTools on Sketch Beta 3.3?

**Comment by turbobabr** [comment]
Hi Yasuaki,

Beta 3.3 isn't supported now, a lot of things had changed and I guess even more might be change prior official release. I'm waiting for stable version and more info about new plugins architecture before making dev tools compatible.

**Comment by uetchy** [comment]
It all makes sense. I actually need your devtools for surveying Sketch's new plugins architecture. Though, I changed the mind and wait for official stable release.
Keep it up!
