### ISSUE TITLE
reinstall of plugins after dev changes - disable the prompts

### ISSUE THREAD

**Issue by ghost** [turbobabr/sketch-devtools#30]
When changes are done we have to manually reinstall the plugin which throws two prompts. one to confirm if install is needed and another when completed.

so frustrating for developers - there needs to be a way to remove these prompts + provide a easy way for npm to trigger automatic install of plugins when developer changes scripts.

![image](https://user-images.githubusercontent.com/13458476/51000383-ae894000-1578-11e9-9cb7-bd3814e921eb.png)

**Comment by turbobabr** [comment]
I tend to think you filed issue to a wrong repo, probably it should be addressed to the official [skpm/sketch-dev-tools](https://github.com/skpm/sketch-dev-tools) package?
